[connections.mydb]
driver = "postgresql+psycopg2"
user = "${PGUSER}"
password = "${PGPASSWORD}"
host = "${PGHOST}"
port = "${PGPORT}"
database = "${PGDATABASE}"

url = "${driver}://${user}:${password}@${host}:${port}/${database}"
